# Generated by Django 5.2.17 on 2026-10-03 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinal',
            name='tipo',
            field=models.CharField(choices=[('ESTATICO', 'Estático'), ('MOVIMENTO', 'Movimento')], default='ESTATICO', max_length=20, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='AmostraMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_frames', models.PositiveIntegerField(verbose_name='quantidade de frames')),
                ('duracao_ms', models.PositiveIntegerField(verbose_name='duração (ms)')),
                ('arquivo_dados', models.CharField(max_length=255, verbose_name='arquivo de dados')),
                ('fps', models.FloatField(default=0.0, verbose_name='fps')),
                ('quantidade_landmarks', models.PositiveIntegerField(default=21, verbose_name='landmarks por frame')),
                ('versao_features', models.PositiveIntegerField(default=1, verbose_name='versão das features')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('sinal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amostras', to='libras.sinal', verbose_name='sinal')),
            ],
            options={
                'verbose_name': 'amostra de movimento',
                'verbose_name_plural': 'amostras de movimento',
                'ordering': ('-criado_em',),
            },
        ),
    ]
