# Generated by Django 5.2.17 on 2026-10-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libras', '0002_sinal_tipo_amostra_movimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinal',
            name='negativo',
            field=models.BooleanField(default=False, help_text='Movimento que NÃO deve ser reconhecido (ex.: J incompleto, I parado). Suas amostras ensinam o modelo a rejeitar.', verbose_name='exemplo negativo'),
        ),
    ]
